package errgen

import (
	"fmt"
	"go/format"
	"strings"
)

const generatedHeader = "Code generated by contracts/cmd/errgen. DO NOT EDIT."

func RenderGo(cat Catalog) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\npackage errors\n\ntype Code string\n\nconst (\n", generatedHeader)
	for _, e := range cat.Errors {
		fmt.Fprintf(&b, "\t%s Code = %q\n", goConst(e.Code), e.Code)
	}
	b.WriteString(")\n\nconst (\n")
	for _, e := range cat.Errors {
		fmt.Fprintf(&b, "\t%s Sentinel = Sentinel(%s)\n", goSentinel(e.Code), goConst(e.Code))
	}
	b.WriteString(")\n\nfunc LookupDefinition(code Code) ErrorDefinition {\n\tswitch code {\n")
	for _, e := range cat.Errors {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn ErrorDefinition{HTTPStatus: %d, Retryable: %t, MessageVI: %q, MessageEN: %q}\n",
			goConst(e.Code), e.Status, e.Retryable, e.Message.VI, e.Message.EN)
	}
	b.WriteString("\tdefault:\n\t\treturn LookupDefinition(CodeInternalError)\n\t}\n}\n")
	return formatGo(b.String())
}

func formatGo(source string) (string, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("gofmt generated code: %w", err)
	}
	return string(formatted), nil
}

func goSentinel(code string) string { return "Err" + strings.TrimPrefix(goConst(code), "Code") }

func goConst(code string) string {
	parts := strings.Split(strings.ToLower(code), "_")
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return "Code" + strings.Join(parts, "")
}
