package errgen

import (
	"fmt"
	"go/format"
	"strings"
)

const generatedHeader = "Code generated by contracts/cmd/errgen. DO NOT EDIT."

func RenderGo(cat Catalog) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\npackage apperr\n\ntype Code string\n\nconst (\n", generatedHeader)
	for _, e := range cat.Errors {
		fmt.Fprintf(&b, "\t%s Code = %q\n", goConst(e.Code), e.Code)
	}
	b.WriteString(")\n\nvar catalog = map[Code]spec{\n")
	for _, e := range cat.Errors {
		fmt.Fprintf(&b, "\t%s: {status: %d, retryable: %t, messageVI: %q, messageEN: %q},\n",
			goConst(e.Code), e.Status, e.Retryable, e.Message.VI, e.Message.EN)
	}
	b.WriteString("}\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt generated code: %w", err)
	}
	return string(formatted), nil
}

func goConst(code string) string {
	parts := strings.Split(strings.ToLower(code), "_")
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return "Code" + strings.Join(parts, "")
}
