// Code generated by contracts/cmd/errorcodegen. DO NOT EDIT.

export const ErrorCode = {
  CONFLICT: "CONFLICT",
  DEPENDENCY_TIMEOUT: "DEPENDENCY_TIMEOUT",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_FOUND: "NOT_FOUND",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  RATE_LIMITED: "RATE_LIMITED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const errorDefinitions: Record<ErrorCode, { httpStatus: number; retryable: boolean; message: { vi: string; en: string } }> = {
  CONFLICT: { httpStatus: 409, retryable: false, message: { vi: "Dữ liệu bị xung đột với trạng thái hiện tại.", en: "The request conflicts with the current state." } },
  DEPENDENCY_TIMEOUT: { httpStatus: 504, retryable: true, message: { vi: "Dịch vụ phụ thuộc phản hồi quá chậm.", en: "A dependency timed out." } },
  FORBIDDEN: { httpStatus: 403, retryable: false, message: { vi: "Bạn không có quyền thực hiện thao tác này.", en: "You are not allowed to do this." } },
  INTERNAL_ERROR: { httpStatus: 500, retryable: false, message: { vi: "Đã có lỗi xảy ra. Vui lòng thử lại.", en: "Something went wrong. Please try again." } },
  METHOD_NOT_ALLOWED: { httpStatus: 405, retryable: false, message: { vi: "Phương thức không được hỗ trợ.", en: "This method is not allowed." } },
  NOT_FOUND: { httpStatus: 404, retryable: false, message: { vi: "Không tìm thấy tài nguyên.", en: "The resource was not found." } },
  PAYLOAD_TOO_LARGE: { httpStatus: 413, retryable: false, message: { vi: "Dữ liệu gửi lên quá lớn.", en: "The request payload is too large." } },
  PROVIDER_UNAVAILABLE: { httpStatus: 503, retryable: true, message: { vi: "Dịch vụ bên ngoài đang không khả dụng.", en: "An upstream provider is unavailable." } },
  RATE_LIMITED: { httpStatus: 429, retryable: true, message: { vi: "Quá nhiều yêu cầu, vui lòng thử lại sau.", en: "Too many requests, please retry later." } },
  UNAUTHENTICATED: { httpStatus: 401, retryable: false, message: { vi: "Bạn cần đăng nhập.", en: "You need to sign in." } },
  VALIDATION_FAILED: { httpStatus: 400, retryable: false, message: { vi: "Dữ liệu gửi lên không hợp lệ.", en: "The request data is invalid." } },
};
