// Code generated by contracts/cmd/errgen. DO NOT EDIT.

package apperr

type Code string

const (
	CodeConflict            Code = "CONFLICT"
	CodeDependencyTimeout   Code = "DEPENDENCY_TIMEOUT"
	CodeForbidden           Code = "FORBIDDEN"
	CodeInternalError       Code = "INTERNAL_ERROR"
	CodeMethodNotAllowed    Code = "METHOD_NOT_ALLOWED"
	CodeNotFound            Code = "NOT_FOUND"
	CodePayloadTooLarge     Code = "PAYLOAD_TOO_LARGE"
	CodeProviderUnavailable Code = "PROVIDER_UNAVAILABLE"
	CodeRateLimited         Code = "RATE_LIMITED"
	CodeUnauthenticated     Code = "UNAUTHENTICATED"
	CodeValidationFailed    Code = "VALIDATION_FAILED"
)

var catalog = map[Code]spec{
	CodeConflict:            {status: 409, retryable: false, messageVI: "Dữ liệu bị xung đột với trạng thái hiện tại.", messageEN: "The request conflicts with the current state."},
	CodeDependencyTimeout:   {status: 504, retryable: true, messageVI: "Dịch vụ phụ thuộc phản hồi quá chậm.", messageEN: "A dependency timed out."},
	CodeForbidden:           {status: 403, retryable: false, messageVI: "Bạn không có quyền thực hiện thao tác này.", messageEN: "You are not allowed to do this."},
	CodeInternalError:       {status: 500, retryable: false, messageVI: "Đã có lỗi xảy ra. Vui lòng thử lại.", messageEN: "Something went wrong. Please try again."},
	CodeMethodNotAllowed:    {status: 405, retryable: false, messageVI: "Phương thức không được hỗ trợ.", messageEN: "This method is not allowed."},
	CodeNotFound:            {status: 404, retryable: false, messageVI: "Không tìm thấy tài nguyên.", messageEN: "The resource was not found."},
	CodePayloadTooLarge:     {status: 413, retryable: false, messageVI: "Dữ liệu gửi lên quá lớn.", messageEN: "The request payload is too large."},
	CodeProviderUnavailable: {status: 503, retryable: true, messageVI: "Dịch vụ bên ngoài đang không khả dụng.", messageEN: "An upstream provider is unavailable."},
	CodeRateLimited:         {status: 429, retryable: true, messageVI: "Quá nhiều yêu cầu, vui lòng thử lại sau.", messageEN: "Too many requests, please retry later."},
	CodeUnauthenticated:     {status: 401, retryable: false, messageVI: "Bạn cần đăng nhập.", messageEN: "You need to sign in."},
	CodeValidationFailed:    {status: 400, retryable: false, messageVI: "Dữ liệu gửi lên không hợp lệ.", messageEN: "The request data is invalid."},
}
