// Code generated by contracts/cmd/errgen. DO NOT EDIT.

package apperr

import catalogerrors "github.com/thomasthecoder198/thomastheragx/backend-core/internal/errors"

type Code = catalogerrors.Code

const (
	CodeConflict            = catalogerrors.CodeConflict
	CodeDependencyTimeout   = catalogerrors.CodeDependencyTimeout
	CodeForbidden           = catalogerrors.CodeForbidden
	CodeInternalError       = catalogerrors.CodeInternalError
	CodeMethodNotAllowed    = catalogerrors.CodeMethodNotAllowed
	CodeNotFound            = catalogerrors.CodeNotFound
	CodePayloadTooLarge     = catalogerrors.CodePayloadTooLarge
	CodeProviderUnavailable = catalogerrors.CodeProviderUnavailable
	CodeRateLimited         = catalogerrors.CodeRateLimited
	CodeUnauthenticated     = catalogerrors.CodeUnauthenticated
	CodeValidationFailed    = catalogerrors.CodeValidationFailed
)
