# Code generated by contracts/cmd/errorcodegen. DO NOT EDIT.
from dataclasses import dataclass
from enum import StrEnum
from typing import Final


class ErrorCode(StrEnum):
    CONFLICT = "CONFLICT"
    DEPENDENCY_TIMEOUT = "DEPENDENCY_TIMEOUT"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    NOT_FOUND = "NOT_FOUND"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    VALIDATION_FAILED = "VALIDATION_FAILED"


@dataclass(frozen=True)
class ErrorDefinition:
    http_status: int
    retryable: bool
    message_vi: str
    message_en: str


ERROR_DEFINITIONS: Final[dict[ErrorCode, ErrorDefinition]] = {
    ErrorCode.CONFLICT: ErrorDefinition(http_status=409, retryable=False, message_vi="Dữ liệu bị xung đột với trạng thái hiện tại.", message_en="The request conflicts with the current state."),
    ErrorCode.DEPENDENCY_TIMEOUT: ErrorDefinition(http_status=504, retryable=True, message_vi="Dịch vụ phụ thuộc phản hồi quá chậm.", message_en="A dependency timed out."),
    ErrorCode.FORBIDDEN: ErrorDefinition(http_status=403, retryable=False, message_vi="Bạn không có quyền thực hiện thao tác này.", message_en="You are not allowed to do this."),
    ErrorCode.INTERNAL_ERROR: ErrorDefinition(http_status=500, retryable=False, message_vi="Đã có lỗi xảy ra. Vui lòng thử lại.", message_en="Something went wrong. Please try again."),
    ErrorCode.METHOD_NOT_ALLOWED: ErrorDefinition(http_status=405, retryable=False, message_vi="Phương thức không được hỗ trợ.", message_en="This method is not allowed."),
    ErrorCode.NOT_FOUND: ErrorDefinition(http_status=404, retryable=False, message_vi="Không tìm thấy tài nguyên.", message_en="The resource was not found."),
    ErrorCode.PAYLOAD_TOO_LARGE: ErrorDefinition(http_status=413, retryable=False, message_vi="Dữ liệu gửi lên quá lớn.", message_en="The request payload is too large."),
    ErrorCode.PROVIDER_UNAVAILABLE: ErrorDefinition(http_status=503, retryable=True, message_vi="Dịch vụ bên ngoài đang không khả dụng.", message_en="An upstream provider is unavailable."),
    ErrorCode.RATE_LIMITED: ErrorDefinition(http_status=429, retryable=True, message_vi="Quá nhiều yêu cầu, vui lòng thử lại sau.", message_en="Too many requests, please retry later."),
    ErrorCode.UNAUTHENTICATED: ErrorDefinition(http_status=401, retryable=False, message_vi="Bạn cần đăng nhập.", message_en="You need to sign in."),
    ErrorCode.VALIDATION_FAILED: ErrorDefinition(http_status=400, retryable=False, message_vi="Dữ liệu gửi lên không hợp lệ.", message_en="The request data is invalid."),
}
