package errorcodegen

import (
	"fmt"
	"go/format"
	"strings"
)

const generatedHeader = "Code generated by contracts/cmd/errorcodegen. DO NOT EDIT."

func RenderGo(catalog Catalog) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\npackage errors\n\ntype Code string\n\nconst (\n", generatedHeader)
	for _, definition := range catalog.Errors {
		fmt.Fprintf(&b, "\t%s Code = %q\n", goCodeConstant(definition.Code), definition.Code)
	}
	b.WriteString(")\n\nconst (\n")
	for _, definition := range catalog.Errors {
		fmt.Fprintf(&b, "\t%s NamedError = NamedError(%s)\n", goNamedError(definition.Code), goCodeConstant(definition.Code))
	}
	b.WriteString(")\n\nfunc LookupDefinition(code Code) ErrorDefinition {\n\tswitch code {\n")
	for _, definition := range catalog.Errors {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn ErrorDefinition{HTTPStatus: %d, Retryable: %t, MessageVI: %q, MessageEN: %q}\n",
			goCodeConstant(definition.Code), definition.Status, definition.Retryable, definition.Message.VI, definition.Message.EN)
	}
	b.WriteString("\tdefault:\n\t\treturn LookupDefinition(CodeInternalError)\n\t}\n}\n")
	return formatGo(b.String())
}

func formatGo(source string) (string, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("gofmt generated code: %w", err)
	}
	return string(formatted), nil
}

func goNamedError(code string) string {
	return "Err" + strings.TrimPrefix(goCodeConstant(code), "Code")
}

func goCodeConstant(code string) string {
	parts := strings.Split(strings.ToLower(code), "_")
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return "Code" + strings.Join(parts, "")
}
