// Code generated by contracts/cmd/errgen. DO NOT EDIT.

package errors

type Code string

const (
	CodeConflict            Code = "CONFLICT"
	CodeDependencyTimeout   Code = "DEPENDENCY_TIMEOUT"
	CodeForbidden           Code = "FORBIDDEN"
	CodeInternalError       Code = "INTERNAL_ERROR"
	CodeMethodNotAllowed    Code = "METHOD_NOT_ALLOWED"
	CodeNotFound            Code = "NOT_FOUND"
	CodePayloadTooLarge     Code = "PAYLOAD_TOO_LARGE"
	CodeProviderUnavailable Code = "PROVIDER_UNAVAILABLE"
	CodeRateLimited         Code = "RATE_LIMITED"
	CodeUnauthenticated     Code = "UNAUTHENTICATED"
	CodeValidationFailed    Code = "VALIDATION_FAILED"
)

const (
	ErrConflict            Sentinel = Sentinel(CodeConflict)
	ErrDependencyTimeout   Sentinel = Sentinel(CodeDependencyTimeout)
	ErrForbidden           Sentinel = Sentinel(CodeForbidden)
	ErrInternalError       Sentinel = Sentinel(CodeInternalError)
	ErrMethodNotAllowed    Sentinel = Sentinel(CodeMethodNotAllowed)
	ErrNotFound            Sentinel = Sentinel(CodeNotFound)
	ErrPayloadTooLarge     Sentinel = Sentinel(CodePayloadTooLarge)
	ErrProviderUnavailable Sentinel = Sentinel(CodeProviderUnavailable)
	ErrRateLimited         Sentinel = Sentinel(CodeRateLimited)
	ErrUnauthenticated     Sentinel = Sentinel(CodeUnauthenticated)
	ErrValidationFailed    Sentinel = Sentinel(CodeValidationFailed)
)

func LookupDefinition(code Code) ErrorDefinition {
	switch code {
	case CodeConflict:
		return ErrorDefinition{HTTPStatus: 409, Retryable: false, MessageVI: "Dữ liệu bị xung đột với trạng thái hiện tại.", MessageEN: "The request conflicts with the current state."}
	case CodeDependencyTimeout:
		return ErrorDefinition{HTTPStatus: 504, Retryable: true, MessageVI: "Dịch vụ phụ thuộc phản hồi quá chậm.", MessageEN: "A dependency timed out."}
	case CodeForbidden:
		return ErrorDefinition{HTTPStatus: 403, Retryable: false, MessageVI: "Bạn không có quyền thực hiện thao tác này.", MessageEN: "You are not allowed to do this."}
	case CodeInternalError:
		return ErrorDefinition{HTTPStatus: 500, Retryable: false, MessageVI: "Đã có lỗi xảy ra. Vui lòng thử lại.", MessageEN: "Something went wrong. Please try again."}
	case CodeMethodNotAllowed:
		return ErrorDefinition{HTTPStatus: 405, Retryable: false, MessageVI: "Phương thức không được hỗ trợ.", MessageEN: "This method is not allowed."}
	case CodeNotFound:
		return ErrorDefinition{HTTPStatus: 404, Retryable: false, MessageVI: "Không tìm thấy tài nguyên.", MessageEN: "The resource was not found."}
	case CodePayloadTooLarge:
		return ErrorDefinition{HTTPStatus: 413, Retryable: false, MessageVI: "Dữ liệu gửi lên quá lớn.", MessageEN: "The request payload is too large."}
	case CodeProviderUnavailable:
		return ErrorDefinition{HTTPStatus: 503, Retryable: true, MessageVI: "Dịch vụ bên ngoài đang không khả dụng.", MessageEN: "An upstream provider is unavailable."}
	case CodeRateLimited:
		return ErrorDefinition{HTTPStatus: 429, Retryable: true, MessageVI: "Quá nhiều yêu cầu, vui lòng thử lại sau.", MessageEN: "Too many requests, please retry later."}
	case CodeUnauthenticated:
		return ErrorDefinition{HTTPStatus: 401, Retryable: false, MessageVI: "Bạn cần đăng nhập.", MessageEN: "You need to sign in."}
	case CodeValidationFailed:
		return ErrorDefinition{HTTPStatus: 400, Retryable: false, MessageVI: "Dữ liệu gửi lên không hợp lệ.", MessageEN: "The request data is invalid."}
	default:
		return LookupDefinition(CodeInternalError)
	}
}
